### ISSUE TITLE
Fine-tuning ECG-FM

### ISSUE THREAD

**Issue by FUminlee** [bowang-lab/ECG-FM#4]
Hi,

For fine-tuning, is there any example for MANIFEST_DIR and LABEL_DIR? That is, if I want to try a new dataset with new label, what format should I turn my new dataset into?

Thanks a lot!

**Comment by KadenMc** [comment]
In the `Data Preparation` section of the README, you will see a link which takes you to a directory in `fairseq-signals`, which has its own README explaining the data preparation pipeline. The final section there, `Curating Datasets`, should be what you're looking for!

If you have any further questions, please feel free to create another issue, otherwise you can email me with any suggested clarifications!
